

export const sample_foods:any[] = [
  {
    id:'1',
    name: 'Momos',
    cookTime: '30-40',
    price:5,
    favorite: false,
    stars: 4.5,
    imageUrl: 'assets/food-1.jfif',
    tags: ['Momos'],
  },
  {
    id:'2',
    name: 'paneer Tikka Pizza',
    price: 14,
    cookTime: '30-40',
    favorite: true,
    stars: 4.7,
    imageUrl: 'assets/food-2.jfif',
    tags: ['FastFood','Pizza'],
  },
  {
    id:'3',
    name: ' cheese burger',
    price: 5,
    cookTime: '20-30',
    favorite: false,
    stars: 3.5,
    imageUrl: 'assets/food-3.jfif',
    tags: ['FastFood', 'burger'],
  },
  {
    id:'4',
    name: 'Chicken tikka Masala pizza',
    price: 13,
    cookTime: '40-50',
    favorite: true,
    stars: 3.3,
    imageUrl: 'assets/food-4.jfif',
    tags: ['FastFood', 'Pizza'],
  },
  {
    id:'5',
    name: 'Aloo Paratha',
    price: 12,
    cookTime: '30-50',
    favorite: false,
    stars: 3.0,
    imageUrl: 'assets/food-5.webp',
    tags: ['Lunch'],
  },
  {
    id:'6',
    name: 'Naan with paneer tikka',
    price: 10,
    cookTime: '40-50',
    favorite: false,
    stars: 4.0,
    imageUrl: 'assets/food-6.png',
    tags: [ 'Lunch'],
  },
  {
    id:'7',
    name: 'Indian thali',
    price: 15,
    cookTime: '50-60',
    favorite: false,
    stars: 5.0,
    imageUrl: 'assets/food-7.jfif',
    tags: ['Lunch'],
  },
  {
    id:'8',
    name: 'French fries',
    price: 6,
    cookTime: '20-30',
    favorite: false,
    stars: 3.8,
    imageUrl: 'assets/food-8.jfif',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'9',
    name: 'sandwich',
    price: 5,
    cookTime: '20-30',
    favorite: false,
    stars: 4.5,
    imageUrl: 'assets/food-9.png',
    tags: ['FastFood','Sandwich'],
  },
  {
    id:'10',
    name: 'Carrot pumpkin soup',
    price: 1,
    cookTime: '15-30',
    favorite: false,
    stars: 4.9,
    imageUrl: 'assets/food-10.jfif',
    tags: ['Soup'],
  },
  {
    id:'11',
    name: 'Creamy potato soup',
    price: 2,
    cookTime: '20-30',
    favorite: false,
    stars: 3.8,
    imageUrl: 'assets/food-11.jfif',
    tags: ['Soup'],
  },
  {
  id:'12',
  name: 'Tomato soup',
  price: 5,
  cookTime: '25-30',
  favorite: false,
  stars: 3.0,
  imageUrl: 'assets/food-12.jfif',
  tags: ['Soup'],
},
]

export const sample_tags:any[] = [
  { name: 'All', count: 12 },
  { name: 'FastFood', count: 5},
  { name: 'Pizza', count: 2},
  { name: 'Lunch', count: 3 },
  { name: 'Momos', count: 1 },
  { name: 'burger', count: 1 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 3 },
  {name: 'Sandwich', count: 1},
]
